name: Azure Databricks CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Databricks CLI
      run: |
        wget -O /tmp/databricks-cli.tar.gz https://files.pythonhosted.org/packages/9c/c9/1069d2a8b6728ddc6082df6b8b4864a9e41a9c0f8a3a30643a63664ffea6/databricks-cli-0.14.3.tar.gz
        tar -xzf /tmp/databricks-cli.tar.gz -C /tmp/
        sudo /tmp/databricks-cli-0.14.3/install.sh

    - name: Connect to Azure Databricks
      run: |
        databricks configure --host "https://adb-952660073371703.3.azuredatabricks.net/" --token "dapiaa0068bdd5b891321b73aa61a8d2acba"

    - name: Git Pull
      run: git pull

    - name: Trigger Databricks Job
      run: databricks jobs run-now --job-id 156051470984333
