name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  connect-and-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Connect to Azure Databricks
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Trigger Databricks Staging Job
      run: databricks jobs run-now --job-id 156051470984333 
      env:
        DATABRICKS_HOST: https://adb-952660073371703.3.azuredatabricks.net
        DATABRICKS_TOKEN: dapiaa0068bdd5b891321b73aa61a8d2acba
