name: Azure Databricks CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Connect to Azure Databricks
      env:
        DATABRICKS_HOST: "https://adb-952660073371703.3.azuredatabricks.net/"
        DATABRICKS_TOKEN: "dapiaa0068bdd5b891321b73aa61a8d2acba"
      run: |
        export DATABRICKS_HOST="${DATABRICKS_HOST}"
        export DATABRICKS_TOKEN="${DATABRICKS_TOKEN}"


    - name: Git Pull
      run: git pull

    - name: Trigger Databricks Job
      run: |
        databricks jobs run-now --job-id 156051470984333
      env:
        DATABRICKS_HOST: "https://adb-952660073371703.3.azuredatabricks.net/"
        DATABRICKS_TOKEN: "dapiaa0068bdd5b891321b73aa61a8d2acba"
      
